const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "918617340627"
const SESSION_ID = "PRABATH-MD~qbBBiBKb#nQ0auzos0dZzmFmf2GlWULRgnodOTaeZnYGFFckyJOc"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
